import type { UsageConfig } from '../../usage';

export default {
  name: 'Icon 图标',
  component: 'KyIcon',
  description: '统一预览内置 SVG 与本地 Iconfont 图标，支持尺寸、颜色、旋转和动画。',
  props: [
    {
      name: 'name',
      label: '图标名称',
      type: 'select',
      defaultValue: 'chevron-right',
      options: [
        'chevron-right',
        'chevron-left',
        'chevron-down',
        'chevron-up',
        'close',
        'check',
        'check-circle',
        'circle',
        'info',
        'help',
        'plus',
        'calendar',
        'trash',
        'edit',
        'copy',
        'bell',
        'speaker',
        'arrow-left',
        'arrow-right',
        'warning',
        'loading',
        'enshrine',
      ],
    },
    { name: 'size', label: '尺寸', type: 'number', defaultValue: 24, min: 12, max: 48, step: 2 },
    {
      name: 'color',
      label: '颜色',
      type: 'select',
      defaultValue: 'var(--ky-color-brand-strong)',
      options: [
        'var(--ky-color-brand-strong)',
        'var(--ky-color-text-primary)',
        'var(--ky-color-text-secondary)',
        'var(--ky-color-danger)',
      ],
    },
    {
      name: 'rotate',
      label: '旋转角度',
      type: 'number',
      defaultValue: 0,
      min: 0,
      max: 360,
      step: 45,
    },
    { name: 'spin', label: '旋转动画', type: 'boolean', defaultValue: false },
  ],
} satisfies UsageConfig;
